import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { School, ShieldCheck, BarChart3, ClipboardCheck, BookOpen, CreditCard, LogIn, UserPlus, ArrowLeft } from 'lucide-react';
import './styles.css';
import SchoolRegistration from './components/SchoolRegistration';
import SchoolAdminDashboard from './components/SchoolAdminDashboard';
import MorningAttendance from './components/MorningAttendance';
import SecureAcademicImport from './components/SecureAcademicImport';
import { loginWithEmail } from './services/authService';

const modules=[['Attendance',ClipboardCheck,'Morning face attendance, QR and manual attendance.','attendance'],['PBD & Peperiksaan',BookOpen,'Secure import, validation and academic analysis.','academic'],['Analytics',BarChart3,'Clear class, subject and student performance trends.','analytics'],['Privacy by Design',ShieldCheck,'School-level isolation and minimized sensitive data.','privacy'],['Subscriptions',CreditCard,'Affordable school plans with school-controlled billing.','plans']];
function Header({onLogin,onHome}){return <nav className="nav"><button className="brand brand-button" onClick={onHome}><div className="brandIcon"><School size={21}/></div><span>MyEduSchool</span></button><button className="login" onClick={onLogin}><LogIn size={16}/> School Login</button></nav>}
function Back({onClick}){return <button className="back-button" onClick={onClick}><ArrowLeft size={16}/> Back</button>}
function Info({title,text,onBack}){return <section className="info-page"><Back onClick={onBack}/><div className="info-card"><span className="eyebrow">MYEDUSCHOOL</span><h1>{title}</h1><p>{text}</p><button className="primary" onClick={onBack}>Return Home</button></div></section>}
function Plans({onRegister}){return <section className="info-page"><div className="info-card"><span className="eyebrow">SCHOOL PLANS</span><h1>Affordable for schools</h1><div className="plan-show"><div><b>Starter · RM19/month</b><span>100 students · core school tools</span></div><div><b>School · RM39/month</b><span>500 students · PBD, exams, face attendance & analytics</span></div><div><b>Pro · RM69/month</b><span>1,500 students · advanced reports & analytics</span></div></div><button className="primary" onClick={onRegister}>Start 14-day trial →</button></div></section>}
function Login({onBack,onSuccess}){const[e,setE]=useState(''),[p,setP]=useState(''),[err,setErr]=useState('');async function submit(x){x.preventDefault();setErr('');try{await loginWithEmail(e,p);onSuccess()}catch(x){setErr(x?.message||'Unable to sign in. Enable Firebase Email/Password Authentication.')}}return <section className="auth-page"><div className="auth-card"><Back onClick={onBack}/><div className="brand auth-brand"><div className="brandIcon"><School size={21}/></div><span>MyEduSchool</span></div><h1>School Login</h1><p>Sign in with your Firebase school account.</p><form onSubmit={submit}><label>Email<input type="email" autoComplete="username" value={e} onChange={x=>setE(x.target.value)} required/></label><label>Password<input type="password" autoComplete="current-password" value={p} onChange={x=>setP(x.target.value)} required/></label>{err&&<div className="error">{err}</div>}<button className="primary full" type="submit">Sign In →</button></form></div></section>}
function App(){const[s,setS]=useState('home'),[school,setSchool]=useState(null);const go=x=>{setS(x);window.scrollTo({top:0,behavior:'smooth'})};const done=x=>{setSchool(x);go('dashboard')};if(s==='register')return <><Header onLogin={()=>go('login')} onHome={()=>go('home')}/><SchoolRegistration onComplete={done}/></>;if(s==='dashboard')return <><Header onLogin={()=>go('home')} onHome={()=>go('home')}/><div className="app-content"><SchoolAdminDashboard school={school} onNavigate={go}/></div></>;if(s==='attendance')return <><Header onLogin={()=>go('login')} onHome={()=>go('dashboard')}/><div className="app-content"><Back onClick={()=>go('dashboard')}/><MorningAttendance school={school}/></div></>;if(s==='academic')return <><Header onLogin={()=>go('login')} onHome={()=>go('dashboard')}/><div className="app-content"><Back onClick={()=>go('dashboard')}/><SecureAcademicImport/></div></>;if(s==='login')return <Login onBack={()=>go('home')} onSuccess={()=>go('dashboard')}/>;if(s==='plans')return <><Header onLogin={()=>go('login')} onHome={()=>go('home')}/><Plans onRegister={()=>go('register')}/></>;if(s==='privacy')return <><Header onLogin={()=>go('login')} onHome={()=>go('home')}/><Info title="Privacy by Design" text="Every school is a separate tenant. Production Firebase rules must enforce schoolId isolation, least privilege and restricted access to sensitive identifiers." onBack={()=>go('home')}/></>;if(s==='analytics')return <><Header onLogin={()=>go('login')} onHome={()=>go('home')}/><Info title="Analytics" text="Analytics combines attendance, PBD and examination records into school, class, subject and student performance views." onBack={()=>go('home')}/></>;return <main className="page"><Header onLogin={()=>go('login')} onHome={()=>go('home')}/><section className="hero"><div className="eyebrow">MALAYSIAN SCHOOL SAAS</div><h1>One smart platform for your <span>school.</span></h1><p>Attendance, homework, PBD, examinations and academic analysis — built as a secure multi-school platform.</p><div className="actions"><button className="primary" onClick={()=>go('register')}><UserPlus size={17}/> Register Your School</button><button className="secondary" onClick={()=>document.getElementById('features')?.scrollIntoView({behavior:'smooth'})}>View Features</button></div><div className="trust"><ShieldCheck size={17}/> Privacy-first architecture · Affordable plans · School-controlled settings</div></section><section id="features" className="modules">{modules.map(([title,Icon,text,action])=><button className="card" key={title} onClick={()=>go(action)}><Icon size={22}/><h3>{title}</h3><p>{text}</p><span>Open module →</span></button>)}</section><footer>MyEduSchool · Built for Malaysian schools · 2026</footer></main>}
createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);
